# This config show which parameter need to enable for KMSCON
# Ideally copy this file to /etc/kmscon/kmscon.conf.example

xkb-layout=us
font-name=Fira Code
font-size=18
palette=soft-black
no-mouse

# GPU acceleration (recommended)
hwaccel
render-engine=gl